name: Testim E2E
on: [push]

jobs:
    run-testimio-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                node-version: '22'
            - run: npm install -g @testim/testim-cli
            - run: testim --token "hbLwxeQduXFEN4CLRafRMbDXGJ5AWbpesXyK1xjcDgVvibS6nt" --project "EosvGsma2F8WUfjl0KaM" --grid "Testim-Grid" --mode "selenium"
